// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3777.BotWars.Commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc3777.BotWars.Robot;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;

/**
 *
 */
public class cmdAutoDrop extends CommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public cmdAutoDrop() {
        addSequential(new cmdAutoDrive());
        addSequential(new cmdAutoHopper());
        addParallel(new cmdAutoHopDrive());
        addSequential(new cmdAutoBack());
        addSequential(new cmdAutoTurn());
    }
}