// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3777.BotWars.Subsystems;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

import org.usfirst.frc3777.BotWars.RobotMap;
import org.usfirst.frc3777.BotWars.Commands.*;

import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
// import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
// import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

// import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class SubSysDrive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// The following declarations, are intended only for use inside this class.
	//		The intent is for that for any access to the motors,
	//		that other parts of this software
	//		must call a method inside this class to access/modify the motors.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX TalonSRXLeftFront = RobotMap.subSysDriveTalonSRXLeftFront;
    private final WPI_TalonSRX TalonSRXLeftBack = RobotMap.subSysDriveTalonSRXLeftBack;
    private final SpeedControllerGroup mtrGroupLeft = RobotMap.subSysDriveMtrGroupLeft;
    private final WPI_VictorSPX VictorSPXightFront = RobotMap.subSysDriveVictorSPXRightFront;
    private final WPI_VictorSPX VictorSPXRightBack = RobotMap.subSysDriveVictorSPXRightBack;
    private final SpeedControllerGroup mtrGroupRight = RobotMap.subSysDriveMtrGroupRight;
    private final DifferentialDrive differentialDrive = RobotMap.subSysDriveDifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    //-------------------------------------------------------------------------
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new cmdDriveTank());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    //-------------------------------------------------------------------------

    public void periodic(double m_leftSpeed, double m_rightSpeed) {
        // Put code here to be run every loop
    	differentialDrive.tankDrive(m_leftSpeed, m_rightSpeed);

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

