// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3777.BotWars.Subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;
//import jdk.internal.loader.AbstractClassLoaderValue.Sub;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
//import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.Spark;
// import edu.wpi.first.wpilibj.SpeedControllerGroup;
import org.usfirst.frc3777.BotWars.RobotMap;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class SubSysSpinner extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    private Spark sparkLeft = RobotMap.subSysSpinnerLeft;
    private Spark sparkRight = RobotMap.subSysSpinnerRight;
	// The following declarations, are intended only for use inside this class.
	//		The intent is for that for any access to the motors,
	//		that other parts of this software
	//		must call a method inside this class to access/modify the motors.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    //private DifferentialDrive sparkDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public SubSysSpinner() {
        
        //sparkLeft = new Spark(0);
        //sparkRight = new Spark(1);


        //sparkDrive = new DifferentialDrive(sparkController, sparkController);
    }

    //-------------------------------------------------------------------------
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());

    }

    //-------------------------------------------------------------------------

    public void periodic() {
        // Put code here to be run every loop

    }


    public void cCWF(){
        sparkLeft.set(.5);
        sparkRight.set(.5);
    }
    public void cCCWF(){
        sparkLeft.set(-.5);
        sparkRight.set(-.5);
    }
    public void cstop(){
        sparkLeft.stopMotor();
        sparkRight.stopMotor();
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

